defmodule Polarex.CheckoutUpdate do
  @moduledoc """
  Provides struct and type for a CheckoutUpdate
  """

  @type t :: %__MODULE__{
          allow_discount_codes: boolean | nil,
          allow_trial: boolean | nil,
          amount: integer | nil,
          currency: String.t() | nil,
          custom_field_data: map | nil,
          customer_billing_address: Polarex.AddressInput.t() | nil,
          customer_billing_name: String.t() | nil,
          customer_email: String.t() | nil,
          customer_ip_address: String.t() | nil,
          customer_metadata: map | nil,
          customer_name: String.t() | nil,
          customer_tax_id: String.t() | nil,
          discount_id: String.t() | nil,
          embed_origin: String.t() | nil,
          is_business_customer: boolean | nil,
          locale: String.t() | nil,
          metadata: map | nil,
          product_id: String.t() | nil,
          product_price_id: String.t() | nil,
          require_billing_address: boolean | nil,
          return_url: String.t() | nil,
          seats: integer | nil,
          success_url: String.t() | nil,
          trial_interval: String.t() | nil,
          trial_interval_count: integer | nil
        }

  defstruct [
    :allow_discount_codes,
    :allow_trial,
    :amount,
    :currency,
    :custom_field_data,
    :customer_billing_address,
    :customer_billing_name,
    :customer_email,
    :customer_ip_address,
    :customer_metadata,
    :customer_name,
    :customer_tax_id,
    :discount_id,
    :embed_origin,
    :is_business_customer,
    :locale,
    :metadata,
    :product_id,
    :product_price_id,
    :require_billing_address,
    :return_url,
    :seats,
    :success_url,
    :trial_interval,
    :trial_interval_count
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      allow_discount_codes: {:union, [:boolean, :null]},
      allow_trial: {:union, [:boolean, :null]},
      amount: {:union, [:integer, :null]},
      currency:
        {:union,
         [
           {:enum,
            [
              "aed",
              "all",
              "amd",
              "aoa",
              "ars",
              "aud",
              "awg",
              "azn",
              "bam",
              "bbd",
              "bdt",
              "bif",
              "bmd",
              "bnd",
              "bob",
              "brl",
              "bsd",
              "bwp",
              "bzd",
              "cad",
              "cdf",
              "chf",
              "clp",
              "cny",
              "cop",
              "crc",
              "cve",
              "czk",
              "djf",
              "dkk",
              "dop",
              "dzd",
              "egp",
              "etb",
              "eur",
              "fjd",
              "fkp",
              "gbp",
              "gel",
              "gip",
              "gmd",
              "gnf",
              "gtq",
              "gyd",
              "hkd",
              "hnl",
              "htg",
              "huf",
              "idr",
              "ils",
              "inr",
              "isk",
              "jmd",
              "jpy",
              "kes",
              "kgs",
              "khr",
              "kmf",
              "krw",
              "kyd",
              "kzt",
              "lak",
              "lkr",
              "lrd",
              "lsl",
              "mad",
              "mdl",
              "mga",
              "mkd",
              "mnt",
              "mop",
              "mur",
              "mvr",
              "mwk",
              "mxn",
              "myr",
              "mzn",
              "nad",
              "ngn",
              "nio",
              "nok",
              "npr",
              "nzd",
              "pab",
              "pen",
              "pgk",
              "php",
              "pkr",
              "pln",
              "pyg",
              "qar",
              "ron",
              "rsd",
              "rwf",
              "sar",
              "sbd",
              "scr",
              "sek",
              "sgd",
              "shp",
              "sos",
              "srd",
              "szl",
              "thb",
              "tjs",
              "top",
              "try",
              "ttd",
              "twd",
              "tzs",
              "uah",
              "ugx",
              "usd",
              "uyu",
              "uzs",
              "vnd",
              "vuv",
              "wst",
              "xaf",
              "xcd",
              "xcg",
              "xof",
              "xpf",
              "yer",
              "zar",
              "zmw"
            ]},
           :null
         ]},
      custom_field_data: :map,
      customer_billing_address: {:union, [{Polarex.AddressInput, :t}, :null]},
      customer_billing_name: {:union, [:string, :null]},
      customer_email: {:union, [{:string, "email"}, :null]},
      customer_ip_address: {:union, [{:string, "ipvanyaddress"}, :null]},
      customer_metadata: {:union, [:map, :null]},
      customer_name: {:union, [:string, :null]},
      customer_tax_id: {:union, [:string, :null]},
      discount_id: {:union, [{:string, "uuid4"}, :null]},
      embed_origin: {:union, [:string, :null]},
      is_business_customer: {:union, [:boolean, :null]},
      locale: {:union, [:string, :null]},
      metadata: :map,
      product_id: {:union, [{:string, "uuid4"}, :null]},
      product_price_id: {:union, [{:string, "uuid4"}, :null]},
      require_billing_address: {:union, [:boolean, :null]},
      return_url: {:union, [{:string, "uri"}, :null]},
      seats: {:union, [:integer, :null]},
      success_url: {:union, [{:string, "uri"}, :null]},
      trial_interval: {:union, [{:enum, ["day", "week", "month", "year"]}, :null]},
      trial_interval_count: {:union, [:integer, :null]}
    ]
  end
end
