defmodule Polarex.DiscountUpdate do
  @moduledoc """
  Provides struct and type for a DiscountUpdate
  """

  @type t :: %__MODULE__{
          amount: integer | nil,
          amounts: map | nil,
          basis_points: integer | nil,
          code: String.t() | nil,
          currency: String.t() | nil,
          duration: String.t() | nil,
          duration_in_months: integer | nil,
          ends_at: DateTime.t() | nil,
          max_redemptions: integer | nil,
          metadata: map | nil,
          name: String.t() | nil,
          products: [String.t()] | nil,
          starts_at: DateTime.t() | nil,
          type: String.t() | nil
        }

  defstruct [
    :amount,
    :amounts,
    :basis_points,
    :code,
    :currency,
    :duration,
    :duration_in_months,
    :ends_at,
    :max_redemptions,
    :metadata,
    :name,
    :products,
    :starts_at,
    :type
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount: {:union, [:integer, :null]},
      amounts: {:union, [:map, :null]},
      basis_points: {:union, [:integer, :null]},
      code: {:union, [:string, :null]},
      currency:
        {:union,
         [
           {:enum,
            [
              "aed",
              "all",
              "amd",
              "aoa",
              "ars",
              "aud",
              "awg",
              "azn",
              "bam",
              "bbd",
              "bdt",
              "bif",
              "bmd",
              "bnd",
              "bob",
              "brl",
              "bsd",
              "bwp",
              "bzd",
              "cad",
              "cdf",
              "chf",
              "clp",
              "cny",
              "cop",
              "crc",
              "cve",
              "czk",
              "djf",
              "dkk",
              "dop",
              "dzd",
              "egp",
              "etb",
              "eur",
              "fjd",
              "fkp",
              "gbp",
              "gel",
              "gip",
              "gmd",
              "gnf",
              "gtq",
              "gyd",
              "hkd",
              "hnl",
              "htg",
              "huf",
              "idr",
              "ils",
              "inr",
              "isk",
              "jmd",
              "jpy",
              "kes",
              "kgs",
              "khr",
              "kmf",
              "krw",
              "kyd",
              "kzt",
              "lak",
              "lkr",
              "lrd",
              "lsl",
              "mad",
              "mdl",
              "mga",
              "mkd",
              "mnt",
              "mop",
              "mur",
              "mvr",
              "mwk",
              "mxn",
              "myr",
              "mzn",
              "nad",
              "ngn",
              "nio",
              "nok",
              "npr",
              "nzd",
              "pab",
              "pen",
              "pgk",
              "php",
              "pkr",
              "pln",
              "pyg",
              "qar",
              "ron",
              "rsd",
              "rwf",
              "sar",
              "sbd",
              "scr",
              "sek",
              "sgd",
              "shp",
              "sos",
              "srd",
              "szl",
              "thb",
              "tjs",
              "top",
              "try",
              "ttd",
              "twd",
              "tzs",
              "uah",
              "ugx",
              "usd",
              "uyu",
              "uzs",
              "vnd",
              "vuv",
              "wst",
              "xaf",
              "xcd",
              "xcg",
              "xof",
              "xpf",
              "yer",
              "zar",
              "zmw"
            ]},
           :null
         ]},
      duration: {:union, [{:enum, ["once", "forever", "repeating"]}, :null]},
      duration_in_months: {:union, [:integer, :null]},
      ends_at: {:union, [{:string, "date-time"}, :null]},
      max_redemptions: {:union, [:integer, :null]},
      metadata: :map,
      name: {:union, [:string, :null]},
      products: {:union, [[string: "uuid4"], :null]},
      starts_at: {:union, [{:string, "date-time"}, :null]},
      type: {:union, [{:enum, ["fixed", "percentage"]}, :null]}
    ]
  end
end
