defmodule Polarex.MetricsTotals do
  @moduledoc """
  Provides struct and type for a MetricsTotals
  """

  @type t :: %__MODULE__{
          active_subscriptions: integer | number,
          active_user_by_event: integer | number,
          average_order_value: integer | number,
          average_revenue_per_user: integer | number,
          canceled_subscriptions: integer | number,
          canceled_subscriptions_customer_service: integer | number,
          canceled_subscriptions_low_quality: integer | number,
          canceled_subscriptions_missing_features: integer | number,
          canceled_subscriptions_other: integer | number,
          canceled_subscriptions_switched_service: integer | number,
          canceled_subscriptions_too_complex: integer | number,
          canceled_subscriptions_too_expensive: integer | number,
          canceled_subscriptions_unused: integer | number,
          cashflow: integer | number,
          checkouts: integer | number,
          checkouts_conversion: integer | number,
          churn_rate: integer | number,
          committed_monthly_recurring_revenue: integer | number,
          cost_per_user: integer | number,
          costs: integer | number,
          cumulative_costs: integer | number,
          cumulative_revenue: integer | number,
          gross_margin: integer | number,
          gross_margin_percentage: integer | number,
          monthly_recurring_revenue: integer | number,
          net_average_order_value: integer | number,
          net_cumulative_revenue: integer | number,
          net_revenue: integer | number,
          new_subscriptions: integer | number,
          new_subscriptions_net_revenue: integer | number,
          new_subscriptions_revenue: integer | number,
          one_time_products: integer | number,
          one_time_products_net_revenue: integer | number,
          one_time_products_revenue: integer | number,
          orders: integer | number,
          renewed_subscriptions: integer | number,
          renewed_subscriptions_net_revenue: integer | number,
          renewed_subscriptions_revenue: integer | number,
          revenue: integer | number,
          succeeded_checkouts: integer | number
        }

  defstruct [
    :active_subscriptions,
    :active_user_by_event,
    :average_order_value,
    :average_revenue_per_user,
    :canceled_subscriptions,
    :canceled_subscriptions_customer_service,
    :canceled_subscriptions_low_quality,
    :canceled_subscriptions_missing_features,
    :canceled_subscriptions_other,
    :canceled_subscriptions_switched_service,
    :canceled_subscriptions_too_complex,
    :canceled_subscriptions_too_expensive,
    :canceled_subscriptions_unused,
    :cashflow,
    :checkouts,
    :checkouts_conversion,
    :churn_rate,
    :committed_monthly_recurring_revenue,
    :cost_per_user,
    :costs,
    :cumulative_costs,
    :cumulative_revenue,
    :gross_margin,
    :gross_margin_percentage,
    :monthly_recurring_revenue,
    :net_average_order_value,
    :net_cumulative_revenue,
    :net_revenue,
    :new_subscriptions,
    :new_subscriptions_net_revenue,
    :new_subscriptions_revenue,
    :one_time_products,
    :one_time_products_net_revenue,
    :one_time_products_revenue,
    :orders,
    :renewed_subscriptions,
    :renewed_subscriptions_net_revenue,
    :renewed_subscriptions_revenue,
    :revenue,
    :succeeded_checkouts
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      active_subscriptions: {:union, [:integer, :number]},
      active_user_by_event: {:union, [:integer, :number]},
      average_order_value: {:union, [:integer, :number]},
      average_revenue_per_user: {:union, [:integer, :number]},
      canceled_subscriptions: {:union, [:integer, :number]},
      canceled_subscriptions_customer_service: {:union, [:integer, :number]},
      canceled_subscriptions_low_quality: {:union, [:integer, :number]},
      canceled_subscriptions_missing_features: {:union, [:integer, :number]},
      canceled_subscriptions_other: {:union, [:integer, :number]},
      canceled_subscriptions_switched_service: {:union, [:integer, :number]},
      canceled_subscriptions_too_complex: {:union, [:integer, :number]},
      canceled_subscriptions_too_expensive: {:union, [:integer, :number]},
      canceled_subscriptions_unused: {:union, [:integer, :number]},
      cashflow: {:union, [:integer, :number]},
      checkouts: {:union, [:integer, :number]},
      checkouts_conversion: {:union, [:integer, :number]},
      churn_rate: {:union, [:integer, :number]},
      committed_monthly_recurring_revenue: {:union, [:integer, :number]},
      cost_per_user: {:union, [:integer, :number]},
      costs: {:union, [:integer, :number]},
      cumulative_costs: {:union, [:integer, :number]},
      cumulative_revenue: {:union, [:integer, :number]},
      gross_margin: {:union, [:integer, :number]},
      gross_margin_percentage: {:union, [:integer, :number]},
      monthly_recurring_revenue: {:union, [:integer, :number]},
      net_average_order_value: {:union, [:integer, :number]},
      net_cumulative_revenue: {:union, [:integer, :number]},
      net_revenue: {:union, [:integer, :number]},
      new_subscriptions: {:union, [:integer, :number]},
      new_subscriptions_net_revenue: {:union, [:integer, :number]},
      new_subscriptions_revenue: {:union, [:integer, :number]},
      one_time_products: {:union, [:integer, :number]},
      one_time_products_net_revenue: {:union, [:integer, :number]},
      one_time_products_revenue: {:union, [:integer, :number]},
      orders: {:union, [:integer, :number]},
      renewed_subscriptions: {:union, [:integer, :number]},
      renewed_subscriptions_net_revenue: {:union, [:integer, :number]},
      renewed_subscriptions_revenue: {:union, [:integer, :number]},
      revenue: {:union, [:integer, :number]},
      succeeded_checkouts: {:union, [:integer, :number]}
    ]
  end
end
