defmodule Polarex.Order do
  @moduledoc """
  Provides struct and type for a Order
  """

  @type t :: %__MODULE__{
          applied_balance_amount: integer,
          billing_address: Polarex.Address.t() | nil,
          billing_name: String.t() | nil,
          billing_reason: String.t(),
          checkout_id: String.t() | nil,
          created_at: DateTime.t(),
          currency: String.t(),
          custom_field_data: Polarex.CustomFieldData.t() | nil,
          customer: Polarex.OrderCustomer.t(),
          customer_id: String.t(),
          description: String.t(),
          discount: map | nil,
          discount_amount: integer,
          discount_id: String.t() | nil,
          due_amount: integer,
          id: String.t(),
          invoice_number: String.t(),
          is_invoice_generated: boolean,
          items: [Polarex.OrderItemSchema.t()],
          metadata: Polarex.Metadata.t(),
          modified_at: DateTime.t() | nil,
          net_amount: integer,
          paid: boolean,
          platform_fee_amount: integer,
          product: Polarex.OrderProduct.t() | nil,
          product_id: String.t() | nil,
          refunded_amount: integer,
          refunded_tax_amount: integer,
          seats: integer | nil,
          status: String.t(),
          subscription: Polarex.OrderSubscription.t() | nil,
          subscription_id: String.t() | nil,
          subtotal_amount: integer,
          tax_amount: integer,
          total_amount: integer,
          user_id: String.t()
        }

  defstruct [
    :applied_balance_amount,
    :billing_address,
    :billing_name,
    :billing_reason,
    :checkout_id,
    :created_at,
    :currency,
    :custom_field_data,
    :customer,
    :customer_id,
    :description,
    :discount,
    :discount_amount,
    :discount_id,
    :due_amount,
    :id,
    :invoice_number,
    :is_invoice_generated,
    :items,
    :metadata,
    :modified_at,
    :net_amount,
    :paid,
    :platform_fee_amount,
    :product,
    :product_id,
    :refunded_amount,
    :refunded_tax_amount,
    :seats,
    :status,
    :subscription,
    :subscription_id,
    :subtotal_amount,
    :tax_amount,
    :total_amount,
    :user_id
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      applied_balance_amount: :integer,
      billing_address: {:union, [{Polarex.Address, :t}, :null]},
      billing_name: {:union, [{:string, :generic}, :null]},
      billing_reason:
        {:enum, ["purchase", "subscription_create", "subscription_cycle", "subscription_update"]},
      checkout_id: {:union, [{:string, :generic}, :null]},
      created_at: {:string, :date_time},
      currency: {:string, :generic},
      custom_field_data: {Polarex.CustomFieldData, :t},
      customer: {Polarex.OrderCustomer, :t},
      customer_id: {:string, :generic},
      description: {:string, :generic},
      discount: {:union, [:map, :null]},
      discount_amount: :integer,
      discount_id: {:union, [{:string, :generic}, :null]},
      due_amount: :integer,
      id: {:string, :generic},
      invoice_number: {:string, :generic},
      is_invoice_generated: :boolean,
      items: [{Polarex.OrderItemSchema, :t}],
      metadata: {Polarex.Metadata, :t},
      modified_at: {:union, [{:string, :date_time}, :null]},
      net_amount: :integer,
      paid: :boolean,
      platform_fee_amount: :integer,
      product: {:union, [{Polarex.OrderProduct, :t}, :null]},
      product_id: {:union, [{:string, :generic}, :null]},
      refunded_amount: :integer,
      refunded_tax_amount: :integer,
      seats: {:union, [:integer, :null]},
      status: {:enum, ["pending", "paid", "refunded", "partially_refunded"]},
      subscription: {:union, [{Polarex.OrderSubscription, :t}, :null]},
      subscription_id: {:union, [{:string, :generic}, :null]},
      subtotal_amount: :integer,
      tax_amount: :integer,
      total_amount: :integer,
      user_id: {:string, :generic}
    ]
  end
end
