defmodule Polarex.Organization do
  @moduledoc """
  Provides struct and type for a Organization
  """

  @type t :: %__MODULE__{
          account_id: String.t() | nil,
          allow_customer_updates: boolean,
          avatar_url: String.t() | nil,
          capabilities: Polarex.OrganizationCapabilities.t(),
          country: String.t() | nil,
          created_at: DateTime.t(),
          customer_email_settings: Polarex.OrganizationCustomerEmailSettings.t(),
          customer_portal_settings: Polarex.OrganizationCustomerPortalSettings.t(),
          default_presentment_currency: String.t(),
          default_tax_behavior: String.t(),
          details_submitted_at: DateTime.t() | nil,
          dispute_settings: Polarex.OrganizationDisputeSettings.t(),
          email: String.t() | nil,
          embed_hosts: [String.t()],
          embed_hosts_enforced: boolean,
          feature_settings: Polarex.OrganizationFeatureSettings.t() | nil,
          id: String.t(),
          modified_at: DateTime.t() | nil,
          name: String.t(),
          onboarding_resubmission_requested_at: DateTime.t() | nil,
          payout_account_id: String.t() | nil,
          proration_behavior: String.t(),
          slug: String.t(),
          socials: [Polarex.OrganizationSocialLink.t()],
          sso_enforced: boolean,
          status: String.t(),
          subscription_settings: Polarex.OrganizationSubscriptionSettings.t(),
          website: String.t() | nil
        }

  defstruct [
    :account_id,
    :allow_customer_updates,
    :avatar_url,
    :capabilities,
    :country,
    :created_at,
    :customer_email_settings,
    :customer_portal_settings,
    :default_presentment_currency,
    :default_tax_behavior,
    :details_submitted_at,
    :dispute_settings,
    :email,
    :embed_hosts,
    :embed_hosts_enforced,
    :feature_settings,
    :id,
    :modified_at,
    :name,
    :onboarding_resubmission_requested_at,
    :payout_account_id,
    :proration_behavior,
    :slug,
    :socials,
    :sso_enforced,
    :status,
    :subscription_settings,
    :website
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      account_id: {:union, [{:string, "uuid4"}, :null]},
      allow_customer_updates: :boolean,
      avatar_url: {:union, [:string, :null]},
      capabilities: {Polarex.OrganizationCapabilities, :t},
      country:
        {:union,
         [
           {:enum,
            [
              "AD",
              "AE",
              "AF",
              "AG",
              "AI",
              "AL",
              "AM",
              "AO",
              "AQ",
              "AR",
              "AS",
              "AT",
              "AU",
              "AW",
              "AX",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BL",
              "BM",
              "BN",
              "BO",
              "BQ",
              "BR",
              "BS",
              "BT",
              "BV",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CC",
              "CD",
              "CF",
              "CG",
              "CH",
              "CI",
              "CK",
              "CL",
              "CM",
              "CN",
              "CO",
              "CR",
              "CU",
              "CV",
              "CW",
              "CX",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "EH",
              "ER",
              "ES",
              "ET",
              "FI",
              "FJ",
              "FK",
              "FM",
              "FO",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GF",
              "GG",
              "GH",
              "GI",
              "GL",
              "GM",
              "GN",
              "GP",
              "GQ",
              "GR",
              "GS",
              "GT",
              "GU",
              "GW",
              "GY",
              "HK",
              "HM",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IM",
              "IN",
              "IO",
              "IQ",
              "IR",
              "IS",
              "IT",
              "JE",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KP",
              "KR",
              "KW",
              "KY",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MF",
              "MG",
              "MH",
              "MK",
              "ML",
              "MM",
              "MN",
              "MO",
              "MP",
              "MQ",
              "MR",
              "MS",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NC",
              "NE",
              "NF",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NU",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PF",
              "PG",
              "PH",
              "PK",
              "PL",
              "PM",
              "PN",
              "PR",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RE",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SB",
              "SC",
              "SD",
              "SE",
              "SG",
              "SH",
              "SI",
              "SJ",
              "SK",
              "SL",
              "SM",
              "SN",
              "SO",
              "SR",
              "SS",
              "ST",
              "SV",
              "SX",
              "SY",
              "SZ",
              "TC",
              "TD",
              "TF",
              "TG",
              "TH",
              "TJ",
              "TK",
              "TL",
              "TM",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "UM",
              "US",
              "UY",
              "UZ",
              "VA",
              "VC",
              "VE",
              "VG",
              "VI",
              "VN",
              "VU",
              "WF",
              "WS",
              "YE",
              "YT",
              "ZA",
              "ZM",
              "ZW"
            ]},
           :null
         ]},
      created_at: {:string, "date-time"},
      customer_email_settings: {Polarex.OrganizationCustomerEmailSettings, :t},
      customer_portal_settings: {Polarex.OrganizationCustomerPortalSettings, :t},
      default_presentment_currency: :string,
      default_tax_behavior: {:enum, ["location", "inclusive", "exclusive"]},
      details_submitted_at: {:union, [{:string, "date-time"}, :null]},
      dispute_settings: {Polarex.OrganizationDisputeSettings, :t},
      email: {:union, [:string, :null]},
      embed_hosts: [:string],
      embed_hosts_enforced: :boolean,
      feature_settings: {:union, [{Polarex.OrganizationFeatureSettings, :t}, :null]},
      id: {:string, "uuid4"},
      modified_at: {:union, [{:string, "date-time"}, :null]},
      name: :string,
      onboarding_resubmission_requested_at: {:union, [{:string, "date-time"}, :null]},
      payout_account_id: {:union, [{:string, "uuid4"}, :null]},
      proration_behavior: {:enum, ["invoice", "prorate", "next_period", "reset"]},
      slug: :string,
      socials: [{Polarex.OrganizationSocialLink, :t}],
      sso_enforced: :boolean,
      status:
        {:enum,
         [
           "created",
           "review",
           "snoozed",
           "denied",
           "active",
           "blocked",
           "offboarding",
           "offboarded"
         ]},
      subscription_settings: {Polarex.OrganizationSubscriptionSettings, :t},
      website: {:union, [:string, :null]}
    ]
  end
end
