defmodule Polarex.ProductPriceFixedCreate do
  @moduledoc """
  Provides struct and type for a ProductPriceFixedCreate
  """

  @type t :: %__MODULE__{
          amount_type: String.t(),
          price_amount: integer,
          price_currency: String.t() | nil,
          tax_behavior: String.t() | nil
        }

  defstruct [:amount_type, :price_amount, :price_currency, :tax_behavior]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount_type: {:const, "fixed"},
      price_amount: :integer,
      price_currency:
        {:enum,
         [
           "aed",
           "all",
           "amd",
           "aoa",
           "ars",
           "aud",
           "awg",
           "azn",
           "bam",
           "bbd",
           "bdt",
           "bif",
           "bmd",
           "bnd",
           "bob",
           "brl",
           "bsd",
           "bwp",
           "bzd",
           "cad",
           "cdf",
           "chf",
           "clp",
           "cny",
           "cop",
           "crc",
           "cve",
           "czk",
           "djf",
           "dkk",
           "dop",
           "dzd",
           "egp",
           "etb",
           "eur",
           "fjd",
           "fkp",
           "gbp",
           "gel",
           "gip",
           "gmd",
           "gnf",
           "gtq",
           "gyd",
           "hkd",
           "hnl",
           "htg",
           "huf",
           "idr",
           "ils",
           "inr",
           "isk",
           "jmd",
           "jpy",
           "kes",
           "kgs",
           "khr",
           "kmf",
           "krw",
           "kyd",
           "kzt",
           "lak",
           "lkr",
           "lrd",
           "lsl",
           "mad",
           "mdl",
           "mga",
           "mkd",
           "mnt",
           "mop",
           "mur",
           "mvr",
           "mwk",
           "mxn",
           "myr",
           "mzn",
           "nad",
           "ngn",
           "nio",
           "nok",
           "npr",
           "nzd",
           "pab",
           "pen",
           "pgk",
           "php",
           "pkr",
           "pln",
           "pyg",
           "qar",
           "ron",
           "rsd",
           "rwf",
           "sar",
           "sbd",
           "scr",
           "sek",
           "sgd",
           "shp",
           "sos",
           "srd",
           "szl",
           "thb",
           "tjs",
           "top",
           "try",
           "ttd",
           "twd",
           "tzs",
           "uah",
           "ugx",
           "usd",
           "uyu",
           "uzs",
           "vnd",
           "vuv",
           "wst",
           "xaf",
           "xcd",
           "xcg",
           "xof",
           "xpf",
           "yer",
           "zar",
           "zmw"
         ]},
      tax_behavior: {:union, [{:enum, ["location", "inclusive", "exclusive"]}, :null]}
    ]
  end
end
